# Generated by Django 5.1.6 on 2025-03-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='request_pdfs/'),
        ),
    ]
