# Generated by Django 5.1.6 on 2025-03-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_system', '0002_request_comments_request_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
