# Generated by Django 4.2.20 on 2025-04-14 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval_system', '0003_request_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='returned',
        ),
    ]
