# Generated by Django 5.1.6 on 2025-04-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval_system', '0003_request_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='returned',
        ),
    ]
