# Generated by Django 4.2.20 on 2025-04-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unit_user_unit'),
        ('approval_system', '0004_remove_request_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.unit'),
        ),
    ]
