# Generated by Django 4.2.20 on 2025-04-20 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval_system', '0007_request_approved_at_request_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
